{
  "hash": "b74a219fdb7fa635409d5df2071d109a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"12. Prediction and Fit\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n---\n\n# 12. Prediction and Fit\n\n\n## Purpose\n\nRegression models can be used for prediction, but prediction is useful only when model performance is assessed carefully. This chapter uses the Milk Data model to explain fitted values, residuals, R², MAE, and RMSE.\n\n## Applied Question\n\nIn Chapter 10 we estimated:\n\n$$\n\\widehat{Price}=516.6+417.0\\times Volume1000\n$$\n\nCan this equation predict milk prices well?\n\n## Fitted Values\n\nA fitted value is the value predicted by the regression equation:\n\n$$\n\\widehat{Y}\n$$\n\n::: {#e652509c .cell execution_count=2}\n``` {.python .cell-code}\nX = sm.add_constant(milk_data[\"Volume1000\"])\ny = milk_data[\"Price\"]\nmodel = sm.OLS(y, X).fit()\nmilk_data[\"Predicted\"] = model.predict(X)\nmilk_data[[\"Price\", \"Predicted\"]].head()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Price</th>\n      <th>Predicted</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>490</td>\n      <td>884.955783</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1960</td>\n      <td>2136.034010</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1980</td>\n      <td>2044.288273</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>540</td>\n      <td>780.699264</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>490</td>\n      <td>884.955783</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Prediction Errors\n\nThe residual is:\n\n$$\nResidual_i = Actual_i - Predicted_i\n$$\n\n::: {#9701e49a .cell execution_count=3}\n``` {.python .cell-code}\nmilk_data[\"Residual\"] = milk_data[\"Price\"] - milk_data[\"Predicted\"]\n```\n:::\n\n\nResiduals measure prediction error.\n\n## Goodness of Fit\n\nThe model produces:\n\n$$\nR^2 = 0.274\n$$\n\nPackage volume explains approximately 27.4% of the variation in milk prices. The remaining 72.6% is explained by other factors not included in this simple model.\n\n::: {#29df9536 .cell execution_count=4}\n``` {.python .cell-code}\nmodel.rsquared\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\nnp.float64(0.2738783999829125)\n```\n:::\n:::\n\n\n## Prediction Accuracy\n\nUsing the actual Milk Data regression:\n\n$$\nMAE = 437.6\n$$\n\n$$\nRMSE = 772.0\n$$\n\nMAE means that predictions differ from actual prices by about 438 price units on average. RMSE is larger because it penalizes large prediction errors more strongly.\n\n::: {#c718e594 .cell execution_count=5}\n``` {.python .cell-code}\nmae = mean_absolute_error(milk_data[\"Price\"], milk_data[\"Predicted\"])\nrmse = root_mean_squared_error(milk_data[\"Price\"], milk_data[\"Predicted\"])\nmae, rmse\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n(437.567808553386, 772.0000524580844)\n```\n:::\n:::\n\n\n## Actual Versus Predicted Plot\n\n::: {#1fbd4998 .cell execution_count=6}\n``` {.python .cell-code}\nplt.scatter(milk_data[\"Price\"], milk_data[\"Predicted\"])\nplt.xlabel(\"Actual Price\")\nplt.ylabel(\"Predicted Price\")\nplt.title(\"Actual versus Predicted Prices\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](chapter-12-prediction-and-goodness-of-fit_files/figure-html/cell-7-output-1.png){width=602 height=449}\n:::\n:::\n\n\n## Residual Plot\n\n::: {#a823f9d5 .cell execution_count=7}\n``` {.python .cell-code}\nplt.scatter(milk_data[\"Predicted\"], milk_data[\"Residual\"])\nplt.axhline(y=0, linestyle=\"--\")\nplt.xlabel(\"Predicted Price\")\nplt.ylabel(\"Residual\")\nplt.title(\"Residual Plot\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](chapter-12-prediction-and-goodness-of-fit_files/figure-html/cell-8-output-1.png){width=613 height=449}\n:::\n:::\n\n\nA good residual plot should show random scatter with no systematic pattern.\n\n## Prediction Versus Explanation\n\nPrediction and explanation are related but not identical. Prediction focuses on accuracy. Explanation focuses on economic interpretation. A model can predict well without being causal, and a model can be useful for explanation even with modest prediction power.\n\n::: {.callout-warning}\nA high R² does not prove causality and does not guarantee that the model is correctly specified.\n:::\n\n## What We Learned From the Milk Data\n\n- R² = 0.274\n- MAE = 437.6\n- RMSE = 772.0\n\nVolume is useful but not sufficient. Additional variables are needed to improve prediction and explanation.\n\n## Key Takeaways\n\n- Fitted values are predicted values.\n- Residuals measure prediction errors.\n- Volume explains 27.4% of milk price variation.\n- MAE is approximately 437.6 price units.\n- RMSE is approximately 772.0 price units.\n- Prediction and explanation are distinct objectives.\n\n| Navigation |\n|------------|\n| [← 11. Hypothesis Testing](chapter-11-interval-estimation-and-hypothesis-testing.qmd) \\| [Part III Home](part-iii-regression.qmd) \\| [13. Multiple Regression →](chapter-13-multiple-regression.qmd) |\n\n",
    "supporting": [
      "chapter-12-prediction-and-goodness-of-fit_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}