{
  "hash": "fc9917715e6957289e327951b3e84791",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"11. Hypothesis Testing\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n---\n\n# 11. Hypothesis Testing\n\n\n::: {.callout-tip}\nFor t-tests, confidence intervals, and p-value rules, see [Appendix A. Formula Sheet](../appendices/appendix-a-formula-sheet.qmd).\n:::\n\n## Purpose\n\nChapter 10 estimated a simple regression model relating milk prices to package volume. The slope coefficient was 417.0, but any sample estimate contains uncertainty. This chapter introduces standard errors, confidence intervals, and hypothesis tests using the actual Milk Data results.\n\n## Applied Question\n\nIn Chapter 10 we estimated:\n\n$$\n\\widehat{Price}=516.6+417.0\\times Volume1000\n$$\n\n> Is this relationship statistically significant?\n\n## Estimating the Model\n\n::: {#7ae1cc35 .cell execution_count=2}\n``` {.python .cell-code}\nX = sm.add_constant(milk_data[\"Volume1000\"])\ny = milk_data[\"Price\"]\nmodel = sm.OLS(y, X).fit()\nprint(model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                  Price   R-squared:                       0.274\nModel:                            OLS   Adj. R-squared:                  0.271\nMethod:                 Least Squares   F-statistic:                     96.56\nDate:                Fri, 12 Jun 2026   Prob (F-statistic):           1.53e-19\nTime:                        01:57:26   Log-Likelihood:                -2081.5\nNo. Observations:                 258   AIC:                             4167.\nDf Residuals:                     256   BIC:                             4174.\nDf Model:                           1                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nconst        467.9297     74.683      6.266      0.000     320.858     615.002\nVolume1000   417.0261     42.439      9.826      0.000     333.451     500.601\n==============================================================================\nOmnibus:                      221.760   Durbin-Watson:                   1.652\nProb(Omnibus):                  0.000   Jarque-Bera (JB):             2757.298\nSkew:                           3.610   Prob(JB):                         0.00\nKurtosis:                      17.295   Cond. No.                         3.30\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\n## Point Estimate\n\nThe point estimate for the volume coefficient is:\n\n$$\n\\hat{\\beta}_1 = 417.0\n$$\n\nThis is our best estimate of the average relationship between package volume and price.\n\n## Confidence Interval\n\nThe 95% confidence interval for the volume coefficient is:\n\n$$\n333.45 \\leq \\beta_1 \\leq 500.60\n$$\n\nInterpretation:\n\n> The data suggest that the true effect of a 1,000 ml increase in volume is likely to lie between approximately 333 and 501 price units.\n\n::: {#3969940f .cell execution_count=3}\n``` {.python .cell-code}\nmodel.conf_int()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>const</th>\n      <td>320.857636</td>\n      <td>615.001780</td>\n    </tr>\n    <tr>\n      <th>Volume1000</th>\n      <td>333.451316</td>\n      <td>500.600835</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Standard Errors\n\nA standard error measures the precision of an estimate. Small standard errors imply greater precision. Confidence intervals and hypothesis tests are built from standard errors.\n\n::: {#0134c168 .cell execution_count=4}\n``` {.python .cell-code}\nmodel.bse\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\nconst         74.683401\nVolume1000    42.439379\ndtype: float64\n```\n:::\n:::\n\n\n## Hypothesis Testing\n\nThe null hypothesis is:\n\n$$\nH_0:\\beta_1=0\n$$\n\nThe alternative hypothesis is:\n\n$$\nH_1:\\beta_1\\neq 0\n$$\n\nThe p-value for the volume coefficient is:\n\n```text\np < 0.001\n```\n\n::: {#c4b4f39d .cell execution_count=5}\n``` {.python .cell-code}\nmodel.pvalues\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\nconst         1.564357e-09\nVolume1000    1.525668e-19\ndtype: float64\n```\n:::\n:::\n\n\nBecause the p-value is below 0.05, we reject the null hypothesis.\n\n## Confidence Intervals and Significance\n\nThe confidence interval does not include zero. This agrees with the p-value result. The relationship between volume and price is statistically significant.\n\n## Statistical Significance Versus Economic Significance\n\nStatistical significance asks whether the relationship is likely to be real. Economic significance asks whether the magnitude is large enough to matter.\n\nThe Milk Data coefficient of 417.0 is meaningful because a 1,000 ml increase in package volume is associated with a sizeable increase in price.\n\n::: {.callout-warning}\nA statistically significant coefficient is not automatically a causal effect.\n:::\n\n## What We Learned From the Milk Data\n\n- Estimated coefficient: 417.0\n- 95% confidence interval: [333.45, 500.60]\n- p-value: < 0.001\n\nThe evidence supporting a positive relationship between volume and price is very strong.\n\n## Common Mistakes\n\n::: {.callout-warning}\n### Common Mistake 1\nTreating p-values as measures of economic importance.\n:::\n\n::: {.callout-warning}\n### Common Mistake 2\nIgnoring confidence intervals.\n:::\n\n::: {.callout-warning}\n### Common Mistake 3\nConfusing statistical significance with causality.\n:::\n\n## Key Takeaways\n\n- Regression estimates contain uncertainty.\n- Confidence intervals provide a range of plausible values.\n- The estimated volume coefficient is 417.0.\n- The 95% confidence interval is [333.45, 500.60].\n- The p-value is below 0.001.\n- Economists should interpret coefficients before focusing on p-values.\n\n| Navigation |\n|------------|\n| [← 10. Simple Regression](chapter-10-simple-linear-regression.qmd) \\| [Part III Home](part-iii-regression.qmd) \\| [12. Prediction and Fit →](chapter-12-prediction-and-goodness-of-fit.qmd) |\n\n",
    "supporting": [
      "chapter-11-interval-estimation-and-hypothesis-testing_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}