{
  "hash": "55b88a59ea24d2de8d84428440d8bad1",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Chapter 10. Simple Linear Regression\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n---\n\n# Chapter 10. Simple Linear Regression\n\n\n## Chapter Purpose\n\nEconomists are often interested in understanding how one variable is related to another. Do larger farms produce more output? Does income increase food expenditure? Do larger milk packages sell for higher prices?\n\nSimple linear regression provides a systematic way to answer such questions.\n\nUsing the Milk Data dataset containing 258 milk products, we investigate whether package volume helps explain differences in milk prices.\n\n## Applied Question\n\n> Do larger milk packages tend to have higher prices?\n\nVolume is defined as:\n\n$$\nVolume = Size \\times Pieces\n$$\n\nFor easier interpretation, volume is measured in thousands of milliliters:\n\n::: {#c1c863a2 .cell execution_count=2}\n``` {.python .cell-code}\nmilk_data[\"Volume1000\"] = milk_data[\"Volume\"] / 1000\n```\n:::\n\n\n## Exploring the Relationship\n\n::: {#7b671354 .cell execution_count=3}\n``` {.python .cell-code}\nsns.scatterplot(data=milk_data, x=\"Volume1000\", y=\"Price\")\nplt.title(\"Milk Price and Package Volume\")\nplt.xlabel(\"Volume (1000 ml)\")\nplt.ylabel(\"Price\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](chapter-10-simple-linear-regression_files/figure-html/cell-4-output-1.png){width=601 height=449}\n:::\n:::\n\n\nThe scatterplot suggests that larger packages generally have higher prices. Regression allows us to quantify this relationship.\n\n## The Simple Linear Regression Model\n\n$$\nPrice_i = \\beta_0 + \\beta_1 Volume1000_i + u_i\n$$\n\nwhere \\(Price_i\\) is product price, \\(Volume1000_i\\) is package volume in thousands of milliliters, and \\(u_i\\) is the error term.\n\n## Python Implementation\n\n::: {#e005e2b7 .cell execution_count=4}\n``` {.python .cell-code}\nX = sm.add_constant(milk_data[\"Volume1000\"])\ny = milk_data[\"Price\"]\nmodel = sm.OLS(y, X).fit()\nprint(model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                  Price   R-squared:                       0.274\nModel:                            OLS   Adj. R-squared:                  0.271\nMethod:                 Least Squares   F-statistic:                     96.56\nDate:                Fri, 12 Jun 2026   Prob (F-statistic):           1.53e-19\nTime:                        01:23:52   Log-Likelihood:                -2081.5\nNo. Observations:                 258   AIC:                             4167.\nDf Residuals:                     256   BIC:                             4174.\nDf Model:                           1                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nconst        467.9297     74.683      6.266      0.000     320.858     615.002\nVolume1000   417.0261     42.439      9.826      0.000     333.451     500.601\n==============================================================================\nOmnibus:                      221.760   Durbin-Watson:                   1.652\nProb(Omnibus):                  0.000   Jarque-Bera (JB):             2757.298\nSkew:                           3.610   Prob(JB):                         0.00\nKurtosis:                      17.295   Cond. No.                         3.30\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\n## Estimated Regression Model\n\nUsing OLS, the estimated equation is:\n\n$$\n\\widehat{Price} = 516.6 + 417.0 \\times Volume1000\n$$\n\nbased on 258 observations.\n\n## Interpreting the Intercept\n\nThe intercept is 516.6. This is the predicted price when package volume is zero. Since a package with zero volume does not exist, the intercept has limited economic meaning here. Its main role is positioning the regression line.\n\n## Interpreting the Slope\n\nThe slope coefficient is 417.0.\n\n> A 1,000 ml increase in package volume is associated with an average increase of approximately 417 price units.\n\nThe relationship is positive. Larger packages tend to have higher prices on average.\n\n::: {.callout-note}\nBecause volume is measured in thousands of milliliters, the coefficient has a practical interpretation.\n:::\n\n## Goodness of Fit\n\nThe model produces:\n\n$$\nR^2 = 0.274\n$$\n\nPackage volume explains approximately 27.4% of the variation in milk prices. The remaining variation is explained by factors not included in this simple model, such as brand, fat content, package type, freshness, and flavor.\n\n## Statistical Significance\n\nThe volume coefficient is highly statistically significant:\n\n```text\np < 0.001\n```\n\nThe 95% confidence interval is:\n\n$$\n333.45 \\leq \\beta_1 \\leq 500.60\n$$\n\nThe interval does not contain zero, which supports a positive relationship between volume and price.\n\n## Residuals\n\nNo regression model explains every observation perfectly. The residual is:\n\n$$\nResidual_i = Actual_i - Predicted_i\n$$\n\n::: {#8701d799 .cell execution_count=5}\n``` {.python .cell-code}\nmilk_data[\"Predicted\"] = model.predict(X)\nmilk_data[\"Residual\"] = milk_data[\"Price\"] - milk_data[\"Predicted\"]\n```\n:::\n\n\n## Visualizing the Fitted Regression Line\n\n::: {#9e49291b .cell execution_count=6}\n``` {.python .cell-code}\nsns.regplot(data=milk_data, x=\"Volume1000\", y=\"Price\", scatter_kws={\"alpha\":0.5})\nplt.title(\"OLS Regression Line\")\nplt.xlabel(\"Volume (1000 ml)\")\nplt.ylabel(\"Price\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](chapter-10-simple-linear-regression_files/figure-html/cell-7-output-1.png){width=601 height=449}\n:::\n:::\n\n\n## Actual Versus Predicted Values\n\n::: {#4c918412 .cell execution_count=7}\n``` {.python .cell-code}\nplt.scatter(milk_data[\"Price\"], milk_data[\"Predicted\"])\nplt.xlabel(\"Actual Price\")\nplt.ylabel(\"Predicted Price\")\nplt.title(\"Actual vs Predicted Prices\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](chapter-10-simple-linear-regression_files/figure-html/cell-8-output-1.png){width=602 height=449}\n:::\n:::\n\n\n## Regression Does Not Prove Causality\n\nThe positive coefficient does not necessarily imply that increasing package volume causes price to increase. Premium brands may sell larger products, higher-quality products may come in larger packages, or marketing strategies may differ across package sizes.\n\n::: {.callout-warning}\nA statistically significant coefficient does not automatically imply a causal effect.\n:::\n\n## Common Mistakes\n\n::: {.callout-warning}\n### Common Mistake 1\nInterpreting association as causation.\n:::\n\n::: {.callout-warning}\n### Common Mistake 2\nIgnoring the units of measurement.\n:::\n\n::: {.callout-warning}\n### Common Mistake 3\nOverinterpreting the intercept.\n:::\n\n## Key Takeaways\n\n- The Milk Data regression uses 258 observations.\n- The estimated equation is \\(\\widehat{Price}=516.6+417.0\\times Volume1000\\).\n- A 1,000 ml increase in volume is associated with an average price increase of about 417 price units.\n- The relationship is statistically significant.\n- The model explains 27.4% of the variation in milk prices.\n- Additional factors motivate multiple regression analysis.\n\n| Navigation |\n|------------|\n| [← Part III Home](part-iii-regression.qmd) \\| [Chapter 11 →](chapter-11-interval-estimation-and-hypothesis-testing.qmd) |\n\n",
    "supporting": [
      "chapter-10-simple-linear-regression_files"
    ],
    "filters": [],
    "includes": {}
  }
}