{
  "hash": "f37cb98d039b04a4517ada6f56dbf133",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"13. Multiple Regression\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n---\n\n# 13. Multiple Regression\n\n\n## Purpose\n\nSimple regression showed that larger milk packages tend to have higher prices. However, price may also depend on package size and number of pieces. Multiple regression allows us to study several explanatory variables simultaneously.\n\nThe central idea is:\n\n> Estimate the effect of one variable while holding other variables constant.\n\n## Applied Question\n\n> Does volume still matter after accounting for package size and number of pieces?\n\n## The Multiple Regression Model\n\n$$\nPrice_i = \\beta_0 + \\beta_1 Volume1000_i + \\beta_2 Size1000_i + \\beta_3 Pieces_i + u_i\n$$\n\nwhere Volume1000 is total volume in thousands of milliliters and Size1000 is package size in thousands of milliliters.\n\n## Python Implementation\n\n::: {#f732537c .cell execution_count=2}\n``` {.python .cell-code}\nX = milk_data[[\"Volume1000\", \"Size1000\", \"Pieces\"]]\nX = sm.add_constant(X)\ny = milk_data[\"Price\"]\nmodel_multi = sm.OLS(y, X).fit()\nprint(model_multi.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                  Price   R-squared:                       0.302\nModel:                            OLS   Adj. R-squared:                  0.294\nMethod:                 Least Squares   F-statistic:                     36.59\nDate:                Fri, 12 Jun 2026   Prob (F-statistic):           1.09e-19\nTime:                        01:24:16   Log-Likelihood:                -2076.5\nNo. Observations:                 258   AIC:                             4161.\nDf Residuals:                     254   BIC:                             4175.\nDf Model:                           3                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nconst        290.9660     92.492      3.146      0.002     108.818     473.114\nVolume1000   261.3607     65.404      3.996      0.000     132.558     390.164\nSize1000     270.1869     97.784      2.763      0.006      77.616     462.757\nPieces        61.6742     20.619      2.991      0.003      21.069     102.280\n==============================================================================\nOmnibus:                      229.990   Durbin-Watson:                   1.694\nProb(Omnibus):                  0.000   Jarque-Bera (JB):             3185.494\nSkew:                           3.757   Prob(JB):                         0.00\nKurtosis:                      18.488   Cond. No.                         11.3\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\n## Actual Multiple Regression Results\n\nKey results:\n\n| Variable | Coefficient |\n|---|---:|\n| Volume1000 | 261.36 |\n| Size1000 | included |\n| Pieces | included |\n\nModel performance:\n\n$$\nR^2 = 0.302\n$$\n\nCompared with the simple model:\n\n$$\nR^2 = 0.274\n$$\n\nThe explanatory power improves after including additional variables.\n\n## Why Did the Volume Coefficient Change?\n\nSimple regression coefficient:\n\n$$\n417.0\n$$\n\nMultiple regression coefficient:\n\n$$\n261.4\n$$\n\nThe coefficient decreases because part of the relationship previously attributed to volume is now explained by package size and number of pieces.\n\n## Interpreting the Volume Coefficient\n\n> Holding package size and number of pieces constant, a 1,000 ml increase in total volume is associated with an average increase of approximately 261 price units.\n\nThis phrase, \"holding other variables constant,\" is the defining feature of multiple regression.\n\n::: {.callout-tip}\nThe phrase \"holding other variables constant\" is the key idea behind multiple regression.\n:::\n\n## Control Variables\n\nSize1000 and Pieces are control variables. They help separate the relationship between volume and price from related package characteristics.\n\n## Omitted Variable Bias\n\nIf package size and pieces affect price and are correlated with volume, omitting them may distort the volume coefficient. The reduction from 417.0 to 261.4 illustrates why coefficients often change when controls are added.\n\n## Goodness of Fit\n\nThe improvement in R² is:\n\n$$\n0.302 - 0.274 = 0.028\n$$\n\nThe model still leaves substantial variation unexplained, which motivates adding categorical variables such as Brand and Fat in Chapter 15.\n\n## Key Takeaways\n\n- Most economic outcomes depend on multiple variables.\n- Multiple regression allows economists to hold other variables constant.\n- The Milk Data multiple regression increases R² from 0.274 to 0.302.\n- The volume coefficient decreases from 417.0 to 261.4 after controls are added.\n- Control variables improve interpretation.\n\n| Navigation |\n|------------|\n| [← 12. Prediction and Fit](chapter-12-prediction-and-goodness-of-fit.qmd) \\| [Part III Home](part-iii-regression.qmd) \\| [14. Functional Forms →](chapter-14-functional-forms-and-elasticities.qmd) |\n\n",
    "supporting": [
      "chapter-13-multiple-regression_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}