{
  "hash": "2c6b5f671631852dac407f2c2d93db88",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"15. Dummy Variables\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n---\n\n# 15. Dummy Variables\n\n\n## Purpose\n\nMany product characteristics are qualitative rather than numerical. Brand, fat content, package type, location, and flavor cannot enter regression directly unless they are converted into numerical form. Dummy variables solve this problem.\n\nThis chapter uses the actual Milk Data dataset to estimate how brand and fat content are associated with milk prices after controlling for package volume.\n\n## Applied Question\n\n> Do brand and fat content help explain milk prices after controlling for package volume?\n\n## What Is a Dummy Variable?\n\nA dummy variable takes only two values:\n\n$$\n0 \\quad \\text{or} \\quad 1\n$$\n\nIt indicates whether a characteristic is absent or present.\n\n## Reference Categories\n\nIn this chapter, the reference categories are:\n\n| Variable | Reference Category |\n|---|---|\n| Brand | Almarai |\n| Fat | Full |\n\nAll categorical coefficients are interpreted relative to these reference groups.\n\n::: {.callout-note}\nDummy coefficients are not absolute prices. They are differences relative to the reference category.\n:::\n\n## Regression Model\n\n$$\nPrice_i = \\beta_0 + \\beta_1 Volume1000_i + Brand_i + Fat_i + u_i\n$$\n\n## Python Implementation\n\n::: {#0b4a54b9 .cell execution_count=2}\n``` {.python .cell-code}\nmodel_dummy = smf.ols(\n    'Price ~ Volume1000 + C(Brand, Treatment(reference=\"Almarai\")) + C(Fat, Treatment(reference=\"Full\"))',\n    data=milk_data\n).fit()\nprint(model_dummy.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                  Price   R-squared:                       0.490\nModel:                            OLS   Adj. R-squared:                  0.445\nMethod:                 Least Squares   F-statistic:                     10.81\nDate:                Fri, 12 Jun 2026   Prob (F-statistic):           2.28e-24\nTime:                        01:24:24   Log-Likelihood:                -2035.8\nNo. Observations:                 258   AIC:                             4116.\nDf Residuals:                     236   BIC:                             4194.\nDf Model:                          21                                         \nCovariance Type:            nonrobust                                         \n========================================================================================================================\n                                                           coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------------------------------------------------\nIntercept                                              317.1692    115.421      2.748      0.006      89.782     544.556\nC(Brand, Treatment(reference=\"Almarai\"))[T.Activia]   -139.4504    684.833     -0.204      0.839   -1488.618    1209.717\nC(Brand, Treatment(reference=\"Almarai\"))[T.AlAin]      279.3965    180.433      1.548      0.123     -76.068     634.861\nC(Brand, Treatment(reference=\"Almarai\"))[T.AlMudish]  -505.3474    277.583     -1.821      0.070   -1052.205      41.511\nC(Brand, Treatment(reference=\"Almarai\"))[T.AlRawabi]  -126.8266    351.853     -0.360      0.719    -820.001     566.348\nC(Brand, Treatment(reference=\"Almarai\"))[T.AlSafi]     231.8314    690.133      0.336      0.737   -1127.777    1591.440\nC(Brand, Treatment(reference=\"Almarai\"))[T.Alpro]      686.6883    685.323      1.002      0.317    -663.444    2036.820\nC(Brand, Treatment(reference=\"Almarai\"))[T.Arla]       474.0133    491.535      0.964      0.336    -494.343    1442.370\nC(Brand, Treatment(reference=\"Almarai\"))[T.Balade]     145.7496    351.657      0.414      0.679    -547.037     838.537\nC(Brand, Treatment(reference=\"Almarai\"))[T.Hayatna]     21.0844    402.556      0.052      0.958    -771.977     814.146\nC(Brand, Treatment(reference=\"Almarai\"))[T.KDD]        278.0683    685.246      0.406      0.685   -1071.913    1628.049\nC(Brand, Treatment(reference=\"Almarai\"))[T.Koita]      603.5810    488.556      1.235      0.218    -358.908    1566.070\nC(Brand, Treatment(reference=\"Almarai\"))[T.Lacnor]    -276.2208    146.455     -1.886      0.061    -564.747      12.305\nC(Brand, Treatment(reference=\"Almarai\"))[T.Lulu]       -96.7056    161.223     -0.600      0.549    -414.326     220.914\nC(Brand, Treatment(reference=\"Almarai\"))[T.Marmum]    -242.4741    350.856     -0.691      0.490    -933.685     448.736\nC(Brand, Treatment(reference=\"Almarai\"))[T.Mazoon]    -203.8579    145.869     -1.398      0.164    -491.229      83.514\nC(Brand, Treatment(reference=\"Almarai\"))[T.Nada]      -159.2864    262.207     -0.607      0.544    -675.851     357.278\nC(Brand, Treatment(reference=\"Almarai\"))[T.Other]      815.9841    144.863      5.633      0.000     530.594    1101.374\nC(Brand, Treatment(reference=\"Almarai\"))[T.Watani]     266.6087    256.795      1.038      0.300    -239.294     772.511\nC(Fat, Treatment(reference=\"Full\"))[T.Low]              38.3926    103.947      0.369      0.712    -166.390     243.175\nC(Fat, Treatment(reference=\"Full\"))[T.Other]           589.0777    152.796      3.855      0.000     288.059     890.096\nVolume1000                                             432.7499     39.547     10.943      0.000     354.840     510.660\n==============================================================================\nOmnibus:                      149.606   Durbin-Watson:                   1.773\nProb(Omnibus):                  0.000   Jarque-Bera (JB):             1037.496\nSkew:                           2.286   Prob(JB):                    5.14e-226\nKurtosis:                      11.695   Cond. No.                         33.1\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\n## Actual Regression Results\n\nThe regression uses 258 milk products.\n\n$$\nR^2 = 0.490\n$$\n\n$$\nAdjusted\\;R^2 = 0.445\n$$\n\nThe model explains about 49.0% of the variation in milk prices.\n\n## Main Coefficients\n\n| Variable | Coefficient | Std. Error | p-value |\n|---|---:|---:|---:|\n| Intercept | 317.17 | 115.42 | 0.006 |\n| Volume1000 | 432.75 | 39.55 | <0.001 |\n| Fat: Low | 38.39 | 103.95 | 0.712 |\n| Fat: Other | 589.08 | 152.80 | <0.001 |\n\n## Interpretation of Volume\n\n> Holding brand and fat content constant, a 1,000 ml increase in package volume is associated with an average price increase of about 433 price units.\n\n## Interpreting Fat Coefficients\n\nThe reference group is Full fat.\n\nLow-fat products are estimated to be about 38 price units more expensive than full-fat products, but this difference is not statistically significant.\n\nProducts in the Other fat category are associated with prices about 589 price units higher than full-fat products, holding volume and brand constant. This result is statistically significant.\n\n## Brand Coefficients\n\nThe reference brand is Almarai.\n\n| Brand | Coefficient | Std. Error | p-value |\n|---|---:|---:|---:|\n| Activia | -139.45 | 684.83 | 0.839 |\n| AlAin | 279.40 | 180.43 | 0.123 |\n| AlMudish | -505.35 | 277.58 | 0.070 |\n| AlRawabi | -126.83 | 351.85 | 0.719 |\n| AlSafi | 231.83 | 690.13 | 0.737 |\n| Alpro | 686.69 | 685.32 | 0.317 |\n| Arla | 474.01 | 491.53 | 0.336 |\n| Balade | 145.75 | 351.66 | 0.679 |\n| Hayatna | 21.08 | 402.56 | 0.958 |\n| KDD | 278.07 | 685.25 | 0.685 |\n| Koita | 603.58 | 488.56 | 0.218 |\n| Lacnor | -276.22 | 146.45 | 0.061 |\n| Lulu | -96.71 | 161.22 | 0.549 |\n| Marmum | -242.47 | 350.86 | 0.490 |\n| Mazoon | -203.86 | 145.87 | 0.164 |\n| Nada | -159.29 | 262.21 | 0.544 |\n| Other | 815.98 | 144.86 | <0.001 |\n| Watani | 266.61 | 256.79 | 0.300 |\n\n## Interpreting Brand Effects\n\nEvery brand coefficient is interpreted relative to Almarai.\n\nThe Other brand group is associated with prices about 816 price units higher than Almarai products, holding volume and fat content constant. This result is statistically significant.\n\nLacnor products are estimated to be about 276 price units cheaper than Almarai products. This result is marginally significant at the 10% level but not at the 5% level.\n\nAlMudish products are estimated to be about 505 price units cheaper than Almarai products. This result is also marginally significant at the 10% level.\n\n## Important Warning About Small Brand Groups\n\nSome brands appear only a few times in the dataset. Coefficients for small groups should be interpreted cautiously because large standard errors indicate imprecision.\n\n::: {.callout-warning}\nDo not overinterpret dummy coefficients for categories with very few observations.\n:::\n\n## Why R² Increased\n\nThe volume-only model had:\n\n$$\nR^2 = 0.274\n$$\n\nAfter adding brand and fat:\n\n$$\nR^2 = 0.490\n$$\n\nBrand and fat content contain useful economic information.\n\n## The Dummy Variable Trap\n\nIf a categorical variable has \\(K\\) categories, include only \\(K-1\\) dummy variables. The omitted category becomes the reference group. Including all categories with an intercept creates perfect multicollinearity.\n\n## Key Takeaways\n\n- Dummy variables allow qualitative characteristics to enter regression models.\n- The reference brand is Almarai.\n- The reference fat category is Full.\n- Holding brand and fat constant, a 1,000 ml increase in volume is associated with a price increase of about 433 units.\n- Adding brand and fat increases R² from 0.274 to 0.490.\n- The Other fat category and Other brand group are statistically significant.\n- Some brand coefficients are imprecise because of small category counts.\n\n| Navigation |\n|------------|\n| [← 14. Functional Forms](chapter-14-functional-forms-and-elasticities.qmd) \\| [Part III Home](part-iii-regression.qmd) \\| [16. Model Selection →](chapter-16-model-specification-and-f-tests.qmd) |\n\n",
    "supporting": [
      "chapter-15-dummy-variables-and-categorical-factors_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}