{
  "hash": "18af98cf96d33c47ccc60cc1dc95ce2b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"14. Functional Forms\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n---\n\n# 14. Functional Forms\n\n\n::: {.callout-tip}\nFor log-linear, linear-log, and log-log interpretation rules, see [Appendix A. Formula Sheet](../appendices/appendix-a-formula-sheet.qmd).\n:::\n\n## Purpose\n\nA regression model may be statistically correct but economically inappropriate if the wrong functional form is chosen. This chapter compares linear, quadratic, and log-log specifications using the actual Milk Data dataset.\n\n## Applied Question\n\n> Is a linear model the best way to describe the relationship between volume and price?\n\n## Linear Model\n\nThe simple linear model is:\n\n$$\nPrice = 516.6 + 417.0 Volume1000\n$$\n\nwith:\n\n$$\nR^2 = 0.274\n$$\n\nIt assumes a constant marginal effect of volume.\n\n## Quadratic Model\n\nA quadratic model allows the marginal effect to change:\n\n$$\nPrice = \\beta_0 + \\beta_1 Volume1000 + \\beta_2 Volume1000^2 + u\n$$\n\n::: {#6108140b .cell execution_count=2}\n``` {.python .cell-code}\nmilk_data[\"Volume1000_sq\"] = milk_data[\"Volume1000\"] ** 2\nXq = sm.add_constant(milk_data[[\"Volume1000\", \"Volume1000_sq\"]])\nmodel_quad = sm.OLS(milk_data[\"Price\"], Xq).fit()\nprint(model_quad.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                  Price   R-squared:                       0.312\nModel:                            OLS   Adj. R-squared:                  0.307\nMethod:                 Least Squares   F-statistic:                     57.89\nDate:                Fri, 12 Jun 2026   Prob (F-statistic):           1.87e-21\nTime:                        01:57:31   Log-Likelihood:                -2074.5\nNo. Observations:                 258   AIC:                             4155.\nDf Residuals:                     255   BIC:                             4166.\nDf Model:                           2                                         \nCovariance Type:            nonrobust                                         \n=================================================================================\n                    coef    std err          t      P>|t|      [0.025      0.975]\n---------------------------------------------------------------------------------\nconst           135.4330    114.343      1.184      0.237     -89.744     360.611\nVolume1000      978.0156    154.381      6.335      0.000     673.992    1282.039\nVolume1000_sq  -135.9566     36.045     -3.772      0.000    -206.941     -64.973\n==============================================================================\nOmnibus:                      219.467   Durbin-Watson:                   1.727\nProb(Omnibus):                  0.000   Jarque-Bera (JB):             2731.136\nSkew:                           3.552   Prob(JB):                         0.00\nKurtosis:                      17.268   Cond. No.                         24.3\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\nActual quadratic results:\n\n| Variable | Coefficient |\n|---|---:|\n| Volume1000 | 978.02 |\n| Volume1000² | -135.96 |\n\nThe negative squared term indicates diminishing marginal effects. Price rises with volume, but the rate of increase becomes smaller as volume increases.\n\n## Log-Log Model\n\nThe log-log model is:\n\n$$\n\\ln(Price) = \\beta_0 + \\beta_1 \\ln(Volume) + u\n$$\n\n::: {#b1abd891 .cell execution_count=3}\n``` {.python .cell-code}\nmilk_data[\"log_price\"] = np.log(milk_data[\"Price\"])\nmilk_data[\"log_volume\"] = np.log(milk_data[\"Volume\"])\nXlog = sm.add_constant(milk_data[\"log_volume\"])\nmodel_log = sm.OLS(milk_data[\"log_price\"], Xlog).fit()\nprint(model_log.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:              log_price   R-squared:                       0.655\nModel:                            OLS   Adj. R-squared:                  0.654\nMethod:                 Least Squares   F-statistic:                     486.7\nDate:                Fri, 12 Jun 2026   Prob (F-statistic):           3.78e-61\nTime:                        01:57:31   Log-Likelihood:                -196.99\nNo. Observations:                 258   AIC:                             398.0\nDf Residuals:                     256   BIC:                             405.1\nDf Model:                           1                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nconst          1.4065      0.237      5.941      0.000       0.940       1.873\nlog_volume     0.7588      0.034     22.062      0.000       0.691       0.827\n==============================================================================\nOmnibus:                       92.697   Durbin-Watson:                   1.598\nProb(Omnibus):                  0.000   Jarque-Bera (JB):              229.105\nSkew:                           1.702   Prob(JB):                     1.78e-50\nKurtosis:                       6.119   Cond. No.                         51.3\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\nActual log-log result:\n\n$$\n\\hat{\\beta}_1 = 0.759\n$$\n\nwith:\n\n$$\nR^2 = 0.655\n$$\n\n## Elasticity Interpretation\n\nIn a log-log model, the coefficient is an elasticity.\n\n> A 1% increase in package volume is associated with an average increase of approximately 0.759% in price.\n\nIf volume increases by 10%, price is expected to increase by about 7.6%.\n\n## Comparing Models\n\n| Model | R² |\n|---|---:|\n| Linear | 0.274 |\n| Multiple Linear | 0.302 |\n| Log-Log | 0.655 |\n\nThe log-log specification explains substantially more price variation than the level model.\n\n## Why the Elasticity Is Less Than One\n\nBecause 0.759 is less than one, price increases proportionally less than volume. This suggests quantity discounts or scale economies in package pricing.\n\n## Choosing Functional Forms\n\nFunctional form selection should be based on economic theory, visual inspection, statistical performance, and interpretability. A higher R² alone is not enough.\n\n## Common Mistakes\n\n::: {.callout-warning}\n### Common Mistake 1\nUsing logarithms when variables contain zeros or negative values.\n:::\n\n::: {.callout-warning}\n### Common Mistake 2\nInterpreting elasticity coefficients as ordinary level coefficients.\n:::\n\n::: {.callout-warning}\n### Common Mistake 3\nChoosing a model solely because it has a higher R².\n:::\n\n## Key Takeaways\n\n- Functional form matters.\n- The simple linear model explains 27.4% of variation.\n- The log-log model explains 65.5% of variation.\n- The estimated elasticity is 0.759.\n- The quadratic specification reveals diminishing marginal effects.\n- The Milk Data strongly support a nonlinear relationship.\n\n| Navigation |\n|------------|\n| [← 13. Multiple Regression](chapter-13-multiple-regression.qmd) \\| [Part III Home](part-iii-regression.qmd) \\| [15. Dummy Variables →](chapter-15-dummy-variables-and-categorical-factors.qmd) |\n\n",
    "supporting": [
      "chapter-14-functional-forms-and-elasticities_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}